# An example of ClusterConfig object compatible with the "app-dev" quickstart
# profile. See also: https://github.com/weaveworks/eks-quickstart-app-dev
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: CP-Watchtower2
  region: us-west-2

nodeGroups:
  - name: CP-Watchtower2-NodeGroup1
    instanceType: m5.large
    desiredCapacity: 1
    iam:
      withAddonPolicies:
        albIngress: true
        autoScaler: true
        cloudWatch: true

#git:
#  repo:
#    url: "git@github.com:myorg/cluster-21.git"
#    branch: master
#    fluxPath: "flux/"
#    user: "gitops"
#    email: "gitops@climatepros.com"
#  operator:
#    namespace: "flux"
#    withHelm: true
#  bootstrapProfile:
#    source: app-dev
#    revision: master
